// Generated by agent_server/scripts/generate_client_types.py.
// Do not edit by hand.

export interface ActionSuccessResult<TContent> {
  type: "success";
  content: TContent;
}

export interface ActionFailureResult {
  type: "failure";
  error: string;
}

export interface ActionStreamingResult {
  type: "streaming";
  result: string;
}

export type WireActionResult<TContent> =
  | ActionSuccessResult<TContent>
  | ActionFailureResult;

export type ActionResult<TContent> =
  | WireActionResult<TContent>
  | ActionStreamingResult;

export interface ContextInfo {
  estimated_tokens: number;
  context_limit: number;
  usage_percentage: number;
  conversation_messages: number;
  approaching_limit: boolean;
}


export interface ThinkInput {
  focus: string;
}

export interface ThinkOutput {
  thoughts: string;
}

export interface WaitInput {
  reason: string;
}

export interface WaitOutput {
  reason: string;
}

export interface SpeakInput {
  intent: string;
  tone: string | null;
}

export interface SpeakOutput {
  response: string;
}

export interface UpdateMoodInput {
  reason: string;
  new_mood: string;
  intensity: string;
}

export interface UpdateMoodOutput {
  old_mood: string;
  old_intensity: string;
  new_mood: string;
  new_intensity: string;
  reason: string;
}

export interface UpdateAppearanceInput {
  reason: string;
  change_description: string;
}

export interface UpdateAppearanceOutput {
  image_description: string;
  old_appearance: string;
  new_appearance: string;
  reason: string;
  image_result: ImageGenerationToolContent;
}

export interface UpdateEnvironmentInput {
  reason: string;
  change_description: string;
}

export interface UpdateEnvironmentOutput {
  image_description: string;
  old_environment: string;
  new_environment: string;
  reason: string;
  image_result: ImageGenerationToolContent;
}

export interface FetchUrlInput {
  url: string;
  looking_for: string;
}

export interface FetchUrlOutput {
  content_summary: string;
}

export interface SearchWebInput {
  purpose: string;
  query: string;
}

export interface SearchWebOutput {
  query_used: string;
  search_results: SearchResult[];
  total_results_found: number;
}

export interface AddPriorityInput {
  reason: string;
  priority_content: string;
  position: RelativePosition;
}

export interface AddPriorityOutput {
  content: string;
  result: AddPrioritySuccessOutput | AddPriorityDuplicateOutput;
}

export interface RemovePriorityInput {
  reason: string;
  priority_id: string;
}

export interface RemovePriorityOutput {
  priority: Priority;
  reason: string;
}

export interface EvaluatePrioritiesInput {
  focus: string;
}

export interface EvaluatePrioritiesOutput {
  operations: (AddPriorityOp | RemovePriorityOp | MergePrioritiesOp | RefinePriorityOp | ReorderPriorityOp)[];
  operation_results: OperationResult[];
  execution_summary: string;
}

export interface CreativeInspirationInput {
  count: number;
  seed: number | null;
}

export interface CreativeInspirationOutput {
  words: string[];
}

export interface UserInputTrigger {
  timestamp: string;
  type: "user_input";
  content: string;
  user_name: string;
  image_paths: string[] | null;
}

export interface WakeupTrigger {
  timestamp: string;
  type: "wakeup";
}

export interface BirthTrigger {
  timestamp: string;
  type: "birth";
  content: string;
  user_name: string;
  image_paths: string[] | null;
  initial_state: State | null;
}

export interface SummaryRecord {
  summary_text: string;
  insert_at_index: number;
  created_at: string;
}

export interface TriggerHistoryEntry {
  trigger: UserInputTrigger | WakeupTrigger | BirthTrigger;
  actions_taken: Action[];
  timestamp: string;
  end_timestamp: string | null;
  entry_id: string;
  situational_context: string;
  compressed_summary: string | null;
}

export interface TimelineEntryTrigger {
  type: "trigger";
  entry: TriggerHistoryEntry;
}

export interface TimelineEntrySummary {
  type: "summary";
  summary: Summary;
}

export interface PaginationInfo {
  total_items: number;
  page_size: number;
  has_next: boolean;
  has_previous: boolean;
  next_cursor: string | null;
  previous_cursor: string | null;
}

export interface TimelineResponse {
  entries: (TimelineEntryTrigger | TimelineEntrySummary)[];
  pagination: PaginationInfo;
}

export interface TriggerStartedEvent {
  type: "trigger_started";
  trigger: UserInputTrigger | WakeupTrigger | BirthTrigger;
  entry_id: string;
  timestamp: string;
}

export interface ActionStartedEvent {
  type: "action_started";
  entry_id: string;
  action_type: string;
  reasoning: string;
  sequence_number: number;
  action_number: number;
  timestamp: string;
}

export interface ActionProgressEvent {
  type: "action_progress";
  entry_id: string;
  action_type: string;
  partial_result: string;
  sequence_number: number;
  action_number: number;
  timestamp: string;
}

export interface ActionCompletedEvent {
  type: "action_completed";
  action: ThinkActionData | WaitActionData | SpeakActionData | UpdateMoodActionData | UpdateAppearanceActionData | UpdateEnvironmentActionData | FetchUrlActionData | SearchWebActionData | AddPriorityActionData | RemovePriorityActionData | EvaluatePrioritiesActionData | CreativeInspirationActionData;
  entry_id: string;
  sequence_number: number;
  action_number: number;
  timestamp: string;
}

export interface TriggerCompletedEvent {
  type: "trigger_completed";
  entry: TriggerHistoryEntry;
  estimated_tokens: number;
  context_limit: number;
  usage_percentage: number;
  approaching_limit: boolean;
}

export interface AgentErrorEvent {
  type: "error";
  message: string;
  entry_id: string;
}

export interface SummarizationStartedEvent {
  type: "summarization_started";
  entries_to_summarize: number;
  recent_entries_kept: number;
  context_usage_before: number;
}

export interface SummarizationFinishedEvent {
  type: "summarization_finished";
  summary: string;
  entries_summarized: number;
  entries_after: number;
  context_usage_after: number;
}

export interface EventEnvelope {
  type: "event_envelope";
  event_sequence: number;
  trigger_id: string;
  event: TriggerStartedEvent | ActionStartedEvent | ActionProgressEvent | ActionCompletedEvent | TriggerCompletedEvent | AgentErrorEvent | SummarizationStartedEvent | SummarizationFinishedEvent;
}

export interface HydrationResponse {
  type: "hydration_response";
  entries: (TimelineEntryTrigger | TimelineEntrySummary)[];
  pagination: PaginationInfo;
}

export interface AutoWakeupSetRequest {
  enabled: boolean;
}

export interface AutoWakeupSetResponse {
  enabled: boolean;
  message: string;
  timestamp: string;
}

export interface AutoWakeupStatusResponse {
  enabled: boolean;
  delay_seconds: number;
}

export interface ImageUploadResponse {
  id: string;
  size: number;
  url: string;
}

export interface InstalledOllamaModelResponse {
  name: string;
  size: number | null;
  modified_at: string | null;
  digest: string | null;
  details: Record<string, unknown>;
}

export interface InstalledOllamaModelsResponse {
  models: InstalledOllamaModelResponse[];
}

export interface ModelConfigResponse {
  state_initialization_model: string;
  action_planning_model: string;
  situational_analysis_model: string;
  memory_retrieval_model: string;
  memory_formation_model: string;
  trigger_compression_model: string;
  think_action_model: string;
  speak_action_model: string;
  visual_action_model: string;
  fetch_url_action_model: string;
  evaluate_priorities_action_model: string;
  tts_rewrite_model: string;
}

export interface ModelConfigUpdateRequest {
  state_initialization_model: string;
  action_planning_model: string;
  situational_analysis_model: string;
  memory_retrieval_model: string;
  memory_formation_model: string;
  trigger_compression_model: string;
  think_action_model: string;
  speak_action_model: string;
  visual_action_model: string;
  fetch_url_action_model: string;
  evaluate_priorities_action_model: string;
  tts_rewrite_model: string;
}

export interface ModelConfigUpdateResponse {
  message: string;
  timestamp: string;
  config: ModelConfigResponse;
}

export interface OllamaModelMutationResponse {
  name: string;
  message: string;
  timestamp: string;
}

export interface PullOllamaModelRequest {
  name: string;
}

export interface ResetResponse {
  message: string;
  timestamp: string;
}

export interface SupportedModelsResponse {
  models: string[];
  ollama_models: string[];
}

export interface ImageGenerationToolContent {
  type: "image_generated";
  prompt: string;
  chunks: string[] | null;
  image_path: string;
  image_url: string;
  width: number;
  height: number;
  num_inference_steps: number;
  guidance_scale: number;
  negative_prompt: string | null;
  original_description: string | null;
  optimization_confidence: number | null;
  camera_angle: string | null;
  viewpoint: string | null;
  optimization_notes: string | null;
}

export interface SearchResult {
  title: string;
  url: string;
  snippet: string;
}

export interface RelativePosition {
  type: "before" | "after" | "highest" | "lowest";
  relative_to_id: string | null;
}

export interface AddPrioritySuccessOutput {
  reason: string;
  type: "success";
  priority_id: string;
}

export interface AddPriorityDuplicateOutput {
  reason: string;
  type: "duplicate";
  existing_priority_id: string | null;
  existing_priority_content: string | null;
}

export interface Priority {
  id: string;
  content: string;
  created_at: string;
}

export interface AddPriorityOp {
  type: "add";
  reasoning: string;
  content: string;
  position: RelativePosition;
}

export interface RemovePriorityOp {
  type: "remove";
  reasoning: string;
  priority_id: string;
}

export interface MergePrioritiesOp {
  type: "merge";
  reasoning: string;
  priority_ids: string[];
}

export interface RefinePriorityOp {
  type: "refine";
  reasoning: string;
  priority_id: string;
  refinement_guidance: string;
}

export interface ReorderPriorityOp {
  type: "reorder";
  reasoning: string;
  priority_id: string;
  new_position: RelativePosition;
}

export interface OperationResult {
  operation_type: "add" | "remove" | "merge" | "refine" | "reorder";
  success: boolean;
  summary: string;
  created_id: string | null;
  new_index: number | null;
  new_content: string | null;
}

export interface State {
  name: string;
  role: string;
  current_mood: string;
  mood_intensity: string;
  current_appearance: string;
  current_environment: string;
  core_values: Value[];
  current_priorities: Priority[];
  max_priorities: number;
  next_priority_id: number;
}

export interface Summary {
  summary_text: string;
  insert_at_index: number;
  created_at: string;
}

export interface Value {
  id: string;
  content: string;
  strength: string;
  acquired_at: string;
}

export interface ThinkActionData {
  type: "think";
  reasoning: string;
  input: ThinkInput;
  result: WireActionResult<ThinkOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export interface WaitActionData {
  type: "wait";
  reasoning: string;
  input: WaitInput;
  result: WireActionResult<WaitOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export interface SpeakActionData {
  type: "speak";
  reasoning: string;
  input: SpeakInput;
  result: WireActionResult<SpeakOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export interface UpdateMoodActionData {
  type: "update_mood";
  reasoning: string;
  input: UpdateMoodInput;
  result: WireActionResult<UpdateMoodOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export interface UpdateAppearanceActionData {
  type: "update_appearance";
  reasoning: string;
  input: UpdateAppearanceInput;
  result: WireActionResult<UpdateAppearanceOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export interface UpdateEnvironmentActionData {
  type: "update_environment";
  reasoning: string;
  input: UpdateEnvironmentInput;
  result: WireActionResult<UpdateEnvironmentOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export interface FetchUrlActionData {
  type: "fetch_url";
  reasoning: string;
  input: FetchUrlInput;
  result: WireActionResult<FetchUrlOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export interface SearchWebActionData {
  type: "search_web";
  reasoning: string;
  input: SearchWebInput;
  result: WireActionResult<SearchWebOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export interface AddPriorityActionData {
  type: "add_priority";
  reasoning: string;
  input: AddPriorityInput;
  result: WireActionResult<AddPriorityOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export interface RemovePriorityActionData {
  type: "remove_priority";
  reasoning: string;
  input: RemovePriorityInput;
  result: WireActionResult<RemovePriorityOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export interface EvaluatePrioritiesActionData {
  type: "evaluate_priorities";
  reasoning: string;
  input: EvaluatePrioritiesInput;
  result: WireActionResult<EvaluatePrioritiesOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export interface CreativeInspirationActionData {
  type: "get_creative_inspiration";
  reasoning: string;
  input: CreativeInspirationInput;
  result: WireActionResult<CreativeInspirationOutput>;
  duration_ms: number;
  start_timestamp: string;
}

export type ActionData = ThinkActionData | WaitActionData | SpeakActionData | UpdateMoodActionData | UpdateAppearanceActionData | UpdateEnvironmentActionData | FetchUrlActionData | SearchWebActionData | AddPriorityActionData | RemovePriorityActionData | EvaluatePrioritiesActionData | CreativeInspirationActionData;
export type ActionStreamingData = {
  [TType in ActionData["type"]]: {
  type: TType;
  reasoning: string;
  result: ActionStreamingResult;
  duration_ms: number;
  start_timestamp: string;
  }
}[ActionData["type"]];
export type Action = ActionData | ActionStreamingData;
export type Trigger = UserInputTrigger | WakeupTrigger | BirthTrigger;
export type TimelineEntry = TimelineEntryTrigger | TimelineEntrySummary;
export type AgentEvent =
  | TriggerStartedEvent
  | ActionStartedEvent
  | ActionProgressEvent
  | ActionCompletedEvent
  | TriggerCompletedEvent
  | AgentErrorEvent
  | SummarizationStartedEvent
  | SummarizationFinishedEvent;
export type AgentServerEvent = HydrationResponse | EventEnvelope;
export type InstalledOllamaModel = InstalledOllamaModelResponse;


export type ThinkAction = Extract<Action, { type: "think" }>;
export type WaitAction = Extract<Action, { type: "wait" }>;
export type SpeakAction = Extract<Action, { type: "speak" }>;
export type UpdateMoodAction = Extract<Action, { type: "update_mood" }>;
export type UpdateAppearanceAction = Extract<Action, { type: "update_appearance" }>;
export type UpdateEnvironmentAction = Extract<Action, { type: "update_environment" }>;
export type FetchUrlAction = Extract<Action, { type: "fetch_url" }>;
export type SearchWebAction = Extract<Action, { type: "search_web" }>;
export type AddPriorityAction = Extract<Action, { type: "add_priority" }>;
export type RemovePriorityAction = Extract<Action, { type: "remove_priority" }>;
export type EvaluatePrioritiesAction = Extract<Action, { type: "evaluate_priorities" }>;
export type CreativeInspirationAction = Extract<Action, { type: "get_creative_inspiration" }>;
