from datetime import datetime
from typing import Iterator, Protocol

from agent.chain_of_action.action.action_data import ActionData
from agent.chain_of_action.trigger import Trigger
from agent.chain_of_action.trigger_history_entry import TriggerHistoryEntry


class ITriggerHistory(Protocol):
    """Protocol for TriggerHistory implementations."""

    def add_entry(self, entry: TriggerHistoryEntry) -> None: ...
    def update_entry(self, entry: TriggerHistoryEntry) -> None: ...
    def get_first_entry(self) -> TriggerHistoryEntry | None: ...
    def get_last_entry(self) -> TriggerHistoryEntry | None: ...
    def get_entry_by_id(self, entry_id: str) -> TriggerHistoryEntry: ...
    def get_entry_count(self) -> int: ...
    def iter_entries(
        self, reverse: bool, start: int
    ) -> Iterator[TriggerHistoryEntry]: ...
    def get_entry_index(self, entry_id: str) -> int: ...
    def get_last_entry_by_trigger_type(
        self, trigger_type: str
    ) -> TriggerHistoryEntry | None: ...
    def __len__(self) -> int: ...
    def close(self) -> None: ...
