from datetime import datetime
from typing import Protocol

from agent.chain_of_action.action.action_data import ActionData
from agent.chain_of_action.trigger import Trigger
from agent.chain_of_action.trigger_history_entry import TriggerHistoryEntry


class ITriggerHistory(Protocol):
    """Protocol for TriggerHistory implementations."""

    def add_entry(self, entry: TriggerHistoryEntry) -> None: ...
    def update_entry(self, entry: TriggerHistoryEntry) -> None: ...
    def get_all_entries(self) -> list[TriggerHistoryEntry]: ...
    def get_first_entry(self) -> TriggerHistoryEntry | None: ...
    def get_entry_by_id(self, entry_id: str) -> TriggerHistoryEntry: ...
    def get_entry_count(self) -> int: ...
    def __len__(self) -> int: ...
